/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

const LeaderboardEntry = IDL.Record({
  rank: IDL.Nat,
  name: IDL.Text,
  timeMs: IDL.Nat,
  timestamp: IDL.Int,
});

export const idlService = IDL.Service({
  submitLapTime: IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  getLeaderboard: IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeaderboardEntry = IDL.Record({
    rank: IDL.Nat,
    name: IDL.Text,
    timeMs: IDL.Nat,
    timestamp: IDL.Int,
  });
  return IDL.Service({
    submitLapTime: IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    getLeaderboard: IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
